/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LendingPlatformAbi__factory } from "./LendingPlatformAbi__factory";
export { LoanAbi__factory } from "./LoanAbi__factory";
