/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc20MetadataSol from "./IERC20Metadata.sol";
export type { ierc20MetadataSol };
import type * as lendingPlatformSol from "./LendingPlatform.sol";
export type { lendingPlatformSol };
export * as factories from "./factories";
export type { IERC20MetadataAbi } from "./IERC20Metadata.sol/IERC20MetadataAbi";
export { IERC20MetadataAbi__factory } from "./factories/IERC20Metadata.sol/IERC20MetadataAbi__factory";
export type { LendingPlatformAbi } from "./LendingPlatform.sol/LendingPlatformAbi";
export { LendingPlatformAbi__factory } from "./factories/LendingPlatform.sol/LendingPlatformAbi__factory";
export type { LoanAbi } from "./LendingPlatform.sol/LoanAbi";
export { LoanAbi__factory } from "./factories/LendingPlatform.sol/LoanAbi__factory";
