/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as lendingPlatformSol from "./LendingPlatform.sol";
export type { lendingPlatformSol };
export * as factories from "./factories";
export type { ERC20Abi } from "./ERC20.sol/ERC20Abi";
export { ERC20Abi__factory } from "./factories/ERC20.sol/ERC20Abi__factory";
export type { LendingPlatformAbi } from "./LendingPlatform.sol/LendingPlatformAbi";
export { LendingPlatformAbi__factory } from "./factories/LendingPlatform.sol/LendingPlatformAbi__factory";
export type { LoanAbi } from "./LendingPlatform.sol/LoanAbi";
export { LoanAbi__factory } from "./factories/LendingPlatform.sol/LoanAbi__factory";
